model_list:
  - model_name: qwen2.5-instruct
    litellm_params:
      model: ollama/qwen2.5:7b-instruct
      api_base: http://ollama:11434
      stream: true
      temperature: 0.1
      max_tokens: 4000

litellm_settings:
  set_verbose: true
  master_key: "internal-llm-key-change-in-production"

general_settings:
  completion_model: qwen2.5-instruct
